#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")
require "helm_upgrade_logs"

@release_name = ARGV.find { |arg| !arg.start_with?("-") }
@namespace = namespace_from_args(ARGV)

helm_pid = Process.spawn "helm test #{ARGV.join(" ")}"

log_pid = Process.spawn(add_ns("kubectl logs -lapp.kubernetes.io/instance=#{@release_name} -f --all-containers --prefix --ignore-errors=true --max-log-requests=20 --timestamps=true --since=1s"))

Process.wait helm_pid
`kill #{log_pid}`
