#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")
require "helm_upgrade_logs"

@release_name = release_name_from_args(ARGV)
@namespace = namespace_from_args(ARGV)

helm_pid = Process.spawn "helm test #{ARGV.join(" ")}"

logging_params = '-f --all-containers --prefix --ignore-errors=true --max-log-requests=20 --timestamps=true --since=1s';

log_pid = Process.spawn(add_ns("kubectl logs -lapp.kubernetes.io/instance=#{@release_name} #{logging_params}"))

Process.wait helm_pid
helm_status = $CHILD_STATUS.exitstatus
Process.kill("KILL", log_pid)
Process.wait log_pid
exit helm_status
