#!/usr/bin/env ruby
# frozen_string_literal: true

require "open3"
require "fileutils"
$LOAD_PATH.unshift File.join(File.dirname(__FILE__), "..", "lib")
require "helm_upgrade_logs"
UPGRADE_LOG_FOLDER = "helm_upgrade_logs"

@release_name = ARGV.find { |arg| !arg.start_with?("-") }
@namespace = namespace_from_args(ARGV)

@helm_pid = Process.spawn "helm upgrade #{ARGV.join(" ")}"

pods_before_upgrade = read_pods
puts "[INFO] Pods before upgrade #{pods_before_upgrade}" if pods_before_upgrade.size.positive?

event_pid = Process.spawn(add_ns("kubectl get events --watch-only=true"))
service_pid = Process.spawn(add_ns("kubectl get services --watch-only=true"))

wait_for_pod_to_log

@pods = []
@pod_pids = {}

begin
  Process.waitpid(@helm_pid, Process::WNOHANG)
rescue Errno::ECHILD
  `kill #{event_pid}`
  `kill #{service_pid}`
  raise HelmUpgradeLogs::Error, "Failed to find logs before helm finished"
end

FileUtils.mkdir_p UPGRADE_LOG_FOLDER

while Process.waitpid(@helm_pid, Process::WNOHANG).nil?
  pods = read_pods - pods_before_upgrade
  if pods != @pods
    @pods = pods
    puts "[INFO] Pods: #{pods.join(",")}"
    # Could change this each to Parallel.each
    @pods.each do |pod|
      next unless @pod_pids[pod].nil?

      wait_for_specific_pod_to_log pod
      std_out_pid = Process.spawn(
        add_ns("kubectl logs #{pod} -f --all-containers --prefix --ignore-errors=true --timestamps=true")
      )
      logfile_pid = Process.spawn(
        add_ns("kubectl logs #{pod} -f --all-containers --prefix --ignore-errors=true --timestamps=true"),
        out: "#{UPGRADE_LOG_FOLDER}/#{pod.gsub("/", "_")}.log"
      )
      @pod_pids["#{pod}_stdout"] = std_out_pid
      @pod_pids["#{pod}_fileout"] = logfile_pid
    end
  end
  sleep 1
end
helm_status = $CHILD_STATUS.exitstatus
`kill #{event_pid}`
`kill #{service_pid}`
puts @pod_pids if ENV["helm_upgrade_logs_debug"] == "true"
@pod_pids.each do |_pod, pid|
  puts "Terminating #{_pod} #{pid}" if ENV["helm_upgrade_logs_debug"] == "true"
  `kill #{pid}`
end

if ENV["helm_upgrade_logs_error_msg"]
  pod_logs_files = Dir.glob("#{UPGRADE_LOG_FOLDER}/*.log")
  puts "Reading logs from #{pod_logs_files.count} pod logs" if ENV["helm_upgrade_logs_debug"] == "true"
  pod_logs_files.each do |log_file|
    lines = File.readlines log_file
    lines.each_with_index do |line, index|
      next unless line.include?(ENV["helm_upgrade_logs_error_msg"])

      msg = "Helm install error: #{line} from #{log_file} (Line #{index + 1})"
      puts "[ERROR] #{msg}"
      puts "##vso[task.logissue type=error] #{msg}" if ENV["helm_upgrade_logs_ado_error"] == "true"
    end
  end
end
exit helm_status
